services:
  - type: web
    name: digitoyou-finance
    runtime: docker
    plan: free
    repo: https://github.com/Jouider/digitoyou-finance
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /login
    envVars:
      - key: APP_NAME
        value: Finance DigiToYou
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_LOCALE
        value: fr
      - key: APP_FALLBACK_LOCALE
        value: fr
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: local

databases:
  # Optionnel: si tu veux PostgreSQL au lieu de SQLite
  # - name: digitoyou-finance-db
  #   databaseName: finance
  #   user: finance_user
